# Dockerfile

FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y netcat-openbsd gcc libmariadb-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# This ensures permission in container runtime
RUN chmod +x /app/wait-for.sh

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["/app/wait-for.sh", "db:3306", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
